name: api_handler
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.19.2 <3.0.0"
dependencies:
  cupertino_icons: ^1.0.2
  dio: ^5.0.3
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
